[connections.snowflake]
account = "chxqjso-zsb56378"
user = "snowflake1200715"
private_key_file = "../rsa_key.p8"
private_key_file_pwd = "snowflake"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
