[connections.snowflake]
account = "chxqjso-zsb56378"
user = "snowflake1200715"
private_key_file = "../xxx/xxx.p8"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
